version: '3.9'

services:
  db:
    image: postgres:14
    container_name: odoo16_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  odoo:
    image: odoo:16
    container_name: odoo16_app
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo_data:/var/lib/odoo
      # Mapeamos 'odoo_mod' directamente como la carpeta de módulos
      - ./backend/odoo_mod:/mnt/extra-addons
      - ./backend/odoo_mod/odoo_config:/etc/odoo
      - ./backend/odoo_mod/keys:/etc/odoo/keys:ro
    restart: always
    command: >
      odoo --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
      --db-filter=.*

volumes:
  db_data:
  odoo_data:
