[options]
private = /etc/odoo/keys/private.pem
public = /etc/odoo/keys/public.pem
admin_passwd = $pbkdf2-sha512$600000$eS/lvLdWijGmVGotJWQMAQ$mxj68KJMQ/VRbIjbmNk6h1wuouBykpUoJIdelPgmfxFPwnFXvgoGNQRl9itQOKedRoPCjKn5KQ0IeEkKv09tRQ

