[options]
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
list_db = True
private = /etc/odoo/keys/private.pem
public = /etc/odoo/keys/public.pem
admin_passwd = $pbkdf2-sha512$600000$Usq5t/YeI.R8r7X2fu.9Vw$zn2v0BNQgP38MLYEuwnUnuL3iWS.HFKjMKShZuro9HfRKDUHWiIEX/yvAfAWNgSYWNdLeDH9C88SL6Q6gMEL4Q

