[options]
private = /etc/odoo/keys/private.pem
public = /etc/odoo/keys/public.pem
admin_passwd = $pbkdf2-sha512$600000$ZkxpbQ2h9P5faw0BwBjD2A$6M2o6GEqYOsMpYEG7C8lH014amZskCIv3GfIWtnlS/xtoN7DZyfYwEksyf9loHx.3HTrp9.5k5Hw59AFb.zWoA